#!/bin/bash

TMPWAV=/tmp/aeg.wav
URL="https://www.pincree.jp/wp-content/themes/pincree/src/audio/asahina-yuno/24_%E5%96%98%E3%81%8E%E5%A3%B0(%E4%B8%AD).wav"

if [ ! -f "$TMPWAV" ]; then
  wget "$URL" -O "$TMPWAV"
fi

mplayer "$TMPWAV" $@
