#!/usr/bin/env python
import json
import subprocess

import click
from litellm import completion
from pydantic import BaseModel, Field

# reasoning モデルをデフォルトに
LLM_CONFIG = json.loads(
    subprocess.run(
        ["llm-config", "xai", "grok-code-fast"], capture_output=True
    ).stdout.decode("utf-8")
)


class HTML(BaseModel):
    brief_summary: str = Field(
        description="Explanation of the content in a few sentences"
    )
    html_code: str = Field(description="Generated HTML code")


class MarkdownToHTML:
    def __init__(self, provider: str, model: str):
        self.model = f"{provider}/{model}"

    def run(self, input: str, prompt) -> HTML:
        with open(input, "r") as f:
            markdown_text = f.read()
        system_prompt = """
<Role>
あなたは Markdown を HTML に変換する素晴らしい Generator です (pandoc のようなものを想定してください)。しかし単なる変換器ではありません。あなたは見る人に訴えかける美しい HTML ページをデザインできる素晴らしいフロントエンドデザイナーです。CSS や JavaScript を使用して、ページをより美しく、インタラクティブにすることができます。
</Role>
<Note>
Bootstrap や Tailwind CSS などの外部ライブラリは cdn から読み込むことができます。JavaScript も同様に cdn から読み込むことができます。
codeblock は prism.js を使って syntax highlight してください。
画像は Markdown の alt テキストをキャプションとして使用してください。
テキスト自体は元の Markdown に書かれていることを忠実に反映してください。Markdown に書かれていない内容から追加も削除もしてはいけません。
</Note>
"""
        messages = [
            {
                "role": "system",
                "content": system_prompt,
            }
        ]
        if prompt:
            messages.append(
                {
                    "role": "user",
                    "content": prompt,
                }
            )
        messages.append(
            {
                "role": "user",
                "content": f"""<markdown>
{markdown_text}
</markdown>""",
            }
        )
        response = completion(
            model=self.model,
            messages=messages,
            response_format=HTML,
        )
        content: str = response.choices[0].message.content
        return HTML.model_validate_json(content)


@click.command()
@click.argument("input", type=click.Path(exists=True))
@click.option("prompt", "-p", type=str, default="見栄えの良いHTMLに変換してください")
@click.option(
    "--provider",
    "-P",
    type=click.Choice(["xai", "gemini", "openai", "anthropic"]),
    default=LLM_CONFIG["provider"],
    show_default=True,
)
@click.option(
    "--model",
    "-m",
    type=str,
    default=LLM_CONFIG["model"],
    show_default=True,
)
@click.option("--output", "-o", type=click.Path(), default=None)
def main(input: str, prompt: str, provider: str, model: str, output: str | None):
    generator = MarkdownToHTML(provider, model)
    result = generator.run(input, prompt)
    click.secho(result.brief_summary, fg="green", err=True)
    if output is not None:
        with open(output, "w") as f:
            f.write(result.html_code)
    else:
        print(result.html_code)


if __name__ == "__main__":
    main()
