#!/bin/bash

OUT=/tmp/amesh.gif
MAP=/tmp/map.jpg
MASK=/tmp/mask.png
CLOUD=/tmp/cloud.gif

ANIMATION=0
LABEL=0

usage() {
    cat <<EOM
NAME - amesh

SYNOPSIS
    amesh
        current snapshot
    amesh -A
        animated gif
    amesh --label
        insert label

EOM
    exit
}

cloud-dt() {
    offset=${1:-0}
    date -d @"$(( ( $(date "+%s") - 200 ) / 300 * 300 - offset * 300 ))" "+%Y%m%d%H%M"
}

cloud-dt-human() {
    offset=${1:-0}
    LANG=C LC_ALL=C date -d @"$(( ( $(date "+%s") - 200 ) / 300 * 300 - offset * 300 ))"
}

cloud-url() {
    DT=$1
    echo "http://tokyo-ame.jwa.or.jp/mesh/000/${DT}.gif"
}

snap-current() {
    dt=$(cloud-dt $1)
    wget -O $CLOUD $(cloud-url $dt)
    convert $MAP $CLOUD -compose over -composite /tmp/amesh_tmp.jpg
    convert /tmp/amesh_tmp.jpg $MASK -compose over -composite $OUT
    if [ "$LABEL" = 1 ]; then
        mv $OUT /tmp/amesh_tmp.jpg
        DT=$(cloud-dt-human $1)
        convert /tmp/amesh_tmp.jpg \
            -pointsize 13 -fill black -undercolor white -annotate +0+12 "$DT" \
            $OUT
    fi
}

snap-animation() {
    n=$1
    for i in $(seq 0 $((n - 1))); do
        snap-current $i
        mv $OUT "/tmp/amesh.animation.$(printf "%03d" $(( 100 - i )) ).gif"
    done
    convert -layers optimize -loop 0 -delay 20 /tmp/amesh.animation.*.gif $OUT
    rm /tmp/amesh.animation.*.gif
}

while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help )
            usage
            ;;
        -a | -A )
            case "$2" in
                [0-9]* )
                    ANIMATION=$2
                    shift 2
                    ;;
                * )
                    ANIMATION=20
                    shift
                    ;;
            esac
            ;;
        --label | -L )
            LABEL=1
            shift
            ;;
        * )
            OUT=$1
            shift
            ;;
    esac
done

wget -O $MAP http://tokyo-ame.jwa.or.jp/map/map000.jpg
wget -O $MASK http://tokyo-ame.jwa.or.jp/map/msk000.png
if [ "$ANIMATION" -eq 0 ]; then
    snap-current
else
    snap-animation "$ANIMATION"
fi
rm $MAP $MASK $CLOUD /tmp/amesh_tmp.jpg
echo "$OUT generated" >&2
