#!/bin/bash

usage() {
    cat <<EOM
anidb-search [KEYWORDS...]
EOM
}

if [ $# -eq 0 ]; then
    usage
    exit
fi

KWD=$(echo "$@" | uri-encode)

paste \
    <( curl -s "https://anidb.net/anime/?adb.search=${KWD}&do.update=Search&noalias=1" -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0' | web-grep '<table><td><a href="/anime/{}"></a></td></table>' | uniq ) \
    <( curl -s "https://anidb.net/anime/?adb.search=${KWD}&do.update=Search&noalias=1" -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0' | web-grep '<table><td><a href="/anime/{}">{}</a></td></table>' )
