#!/bin/bash

usage() {
  cat << HELP
NAME
  animetick -- animetick

SYNOPSIS
  animetick [ OPTIONS ]

OPTIONS
  --help, -h
  --color, -C
  --delete, -D
HELP
  exit 0
}

#
# global
#
COLOR=0
DELETE=0

#
# parse args
#
while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help )
            usage
            ;;
        --color | -C )
            COLOR=1
            ;;
        --delete | -D )
            DELETE=1
            ;;
        -CD | -DC )
            COLOR=1
            DELETE=1
            ;;
    esac
    shift
done

#
# entry
#

parse-datetime() {
    echo "$1" | sed 's,^\(....\)\(..\)\(..\)T\(..\)\(..\)\(..\),\1-\2-\3 \4:\5,g'
}

URL="http://animetick.net/users/ampeloss/ics?h=00f6a1846575e9eff488e118b7626417"
CURRENT=$(date "+%s")

curl -s "$URL" | tr -d '\r' |
    grep -E '^(DTSTART|SUMMARY)' |
    sed 's/^[^:]*://g' |
    while :; do
        read a; read b;
        [ -z "$a" ] && break

        date="$(parse-datetime "$a")"

        # delete
        if [ $DELETE -eq 1 ]; then
            T=$(date -d "$date" "+%s")
            if [ $T -lt $CURRENT ]; then
                continue
            fi
        fi

        # display
        if [ $COLOR -eq 0 ]; then
            echo "$date $b"
        else
            printf "\x1b[33m$date \x1b[39m$b\x1b[0m\n"
        fi

    done |
    sort
