#!/bin/bash

for dep in pandoc latex; do
    if ! which $dep >/dev/null; then
        echo "$dep required"
        exit 1
    fi
done

BASENAME=
for f in $@; do
    case "$f" in
        *.md )
            BASENAME=${f%.md}
            echo $BASENAME
            ;;
    esac
done

if [ -z "$BASENAME" ]; then
    echo "Error: specify a markdown file (*.md)" >&2
    exit 1
fi

pandoc -o "$BASENAME.tex" -t beamer $@
latex "$BASENAME.tex"
