#!/bin/bash

URL=http://s.cympfh.cc/bun

usage() {
    cat <<EOM
NAME
    bun - Buncho CLI

SYNOPSIS

    bun taiju <weight-gram>
        record taiju in gram && do taiju-plot

    bun taiju-plot
        tweet a graph
EOM
    exit
}

post() {
    curl -s -H "X-KEY: ${IK_KEY}" -XPOST "${URL}/$1" --data @-
}

get() {
    curl -s -X GET "${URL}/$1"
}

taiju() {
    datetime="$(date "+%Y-%m-%d %H:%M")"
    qj -e .datetime="$datetime" .weight=$1 | post taiju
}

taiju-plot() {
    DAT=/tmp/bun.taiju.jsonl
    PNG=/tmp/bun.taiju.png
    get taiju | cut -d '	' -f 2 | jq -r '"\(.datetime) \(.weight)"' > $DAT
    gnuplot <<EOM
    set terminal pngcairo size 1200,600
    set output '${PNG}'

    set title 'Bun taiju (g)'

    set timefmt '%Y-%m-%d %H:%M'
    set xdata time
    set format x '%m/%d'
    set xtics rotate by 45 right
    set ylabel 'weight' tc '#808080'
    set xrange ["2020-09-29":]

    set style line 11 lc rgb '#808080' lt 1 lw 2
    set border 0 back ls 11
    set tics out nomirror

    # Standard grid
    set style line 12 lc rgb '#808080' lt 0 lw 1
    set grid back ls 12

    # main line
    set style line 1 pt 6 lw 2 lc rgb "#00aaaa"

    plot '$DAT' u 1:3 w points ls 1 notitle ,\
        '' u 1:3 smooth sbezier ls 1 notitle ,\
        '< tail -1 $DAT' u 1:(\$3+0.2):(strftime("%m/%d", time(\$1)) . "\n" . sprintf("%.1fg",\$3)) with labels notitle
EOM
    echo
    echo $PNG
}

case "$1" in
    --help | -h | help )
        usage
        ;;
    taiju )
        taiju $2
        taiju-plot
        ;;
    taiju-plot )
        taiju-plot
        ;;
    * )
        usage
        ;;
esac
