#!/bin/bash

URL=http://s.cympfh.cc/bun

usage() {
    cat <<EOM
NAME
    bun - Buncho CLI

SYNOPSIS

    bun taiju <weight-gram>
        record taiju in gram && do taiju-plot

    bun taiju-plot
        tweet a graph

    bun esa
        record esa datetime && do esa-plot

    bun esa-plot
        tweet a graph
EOM
    exit
}

post() {
    KEY=KjYqoBjVPIaAfhwqr
    curl -s -H "X-KEY: $KEY" -XPOST "${URL}/$1" --data @-
}

get() {
    curl -s -X GET "${URL}/$1"
}

taiju() {
    datetime="$(date "+%Y-%m-%d %H:%M")"
    qj -e .datetime="$datetime" .weight=$1 | post taiju
}

taiju-plot() {
    DAT=/tmp/bun.taiju.jsonl
    PNG=/tmp/bun.taiju.png
    get taiju | cut -d '	' -f 2 | jq -r '"\(.datetime) \(.weight)"' > $DAT
    gnuplot <<EOM
    set terminal pngcairo size 1200,600
    set output '${PNG}'

    set title 'Bun taiju (g)'

    set timefmt '%Y-%m-%d %H:%M'
    set xdata time
    set format x '%m/%d'
    set xtics rotate by 45 right
    set ylabel 'weight' tc '#808080'
    set xrange ["2020-09-29":]

    set style line 11 lc rgb '#808080' lt 1 lw 2
    set border 0 back ls 11
    set tics out nomirror

    # Standard grid
    set style line 12 lc rgb '#808080' lt 0 lw 1
    set grid back ls 12

    # main line
    set style line 1 pt 6 lw 2 lc rgb "#00aaaa"

    plot '$DAT' u 1:3 w points ls 1 notitle ,\
        '' u 1:3 smooth sbezier ls 1 notitle ,\
        '< tail -1 $DAT' u 1:(\$3+0.2):(strftime("%m/%d", time(\$1)) . "\n" . sprintf("%.1fg",\$3)) with labels notitle
EOM
    echo $PNG
    tw-cd parametertuning
    tw -f $PNG
}

esa() {
    datetime="$(date "+%Y-%m-%d %H:%M")"
    qj -e .datetime="$datetime" | post esa
}

esa-plot() {
    DAT=/tmp/bun.esa.jsonl
    PNG=/tmp/bun.esa.png
    PNG_ROT=/tmp/bun.esa.rot.png
    get esa | tail -n 8 | cut -d '	' -f 2 | jq -r '"\(.datetime)"' > $DAT
    gnuplot <<EOM
    set terminal pngcairo size 900,400
    set output '${PNG}'

    set title 'Bun esa'

    set timefmt '%Y-%m-%d %H:%M'
    set xdata time
    set format x '%m/%d %H:%M'
    set yrange [0:1]
    unset ylabel
    unset ytics
    unset yzeroaxis

    set style line 11 lc rgb '#808080' lt 1 lw 2
    set border 0 back ls 11

    # xtics
    set xtics 21600 rotate by 90 right
    set mxtics 6

    # grid line
    set style line 12 lc rgb '#808080' lt 0 lw 1
    set grid xtics back ls 12
    set grid mxtics back ls 12

    # main box
    set style line 1 pt 6 lw 2 lc rgb "#00aaaa"
    set style line 2 pt 6 lw 1 lc rgb "#ff8888"

    # box style
    set style fill solid

    plot \\
        '< date "+%Y-%m-%d %H:%M"' u 1:(1):(100) w boxes ls 2 notitle,\\
        '$DAT' u 1:(1):(300) w boxes ls 1 notitle,\\
        '< sed "s/ .*/&&/g" $DAT' u (timecolumn(1) - 2400):(0.15 + 0.1 * \$0):3 with labels rotate by 90 notitle
EOM
    convert $PNG -rotate 90 $PNG_ROT
    echo $PNG_ROT
    tw-cd parametertuning
    tw -f $PNG_ROT
}

case "$1" in
    --help | -h | help )
        usage
        ;;
    taiju )
        taiju $2
        taiju-plot
        ;;
    taiju-plot )
        taiju-plot
        ;;
    esa )
        esa
        esa-plot
        ;;
    esa-plot )
        esa-plot
        ;;
    * )
        usage
        ;;
esac
