#!/bin/bash

case "$1" in
    new )
        cargo atcoder new "$2"
        if [ -f Makefile ]; then
            cp Makefile $2/
        fi
        cd $2/
        ;;
    * )
        cargo atcoder "$@"
        ;;
esac
