#!/usr/bin/env ruby
# vim: set ft=ruby:

require 'date'

def usage
  STDERR.puts "SYNOPSIS"
  STDERR.puts "    calendar [-A num] [-B num] [-f calendarfile] [--color]"
  STDERR.puts "For more detail, please see https://github.com/cympfh/calendar"
  exit 0
end

index = nil
$DIR = nil
$A=30 # in default
$B=0
color = false

# parse args
for i in 0 ... ARGV.length
  arg = ARGV[i]
  if arg == nil or arg == "-h" or arg == "-?" or arg == "--help"
    usage
  elsif arg == "-A"
    $A = ARGV[i+1].to_i
    i += 1
  elsif arg == "-B"
    $B = ARGV[i+1].to_i
    i += 1
  elsif arg == "-f"
    index = File.basename ARGV[i+1]
    $DIR = File.dirname ARGV[i+1]
    i += 1
  elsif arg == "-c" or arg == "--color"
    color = true
  end
end

if index == nil
  usage
end

# collection of [ Date, SrcFile, Content ]
$DICT = []

# read and trace
def read(file)
  lines = File.read($DIR + '/' + file).chomp.split("\n")
  for line in lines
    line = line.chomp
    # ignore line
    if line == "" or line.index("//") == 0
    # #include
    elsif line.index("#") == 0
      if /<[^>]*>/.match(line) == nil
        STDERR.puts "parse error(0): #{line} in #{file}"
      else
        subfile = /<[^>]*>/.match(line)[0][1...-1]
        read subfile
      end
    # date line
    else
      res = false
      if (res = /^(.*)\t(.*)$/.match line) != nil
        date = Date.parse(res[1])
        content = res[2]
        $DICT << [date, file, content]
      else
        STDERR.puts "parse error(1): #{line} in #{file}"
      end
    end
  end
end

#
# main
#
read(index)

colhash = {}
$DICT.sort!
from = Date.today - 1 - $B
to = Date.today + $A
for i in 0 ... $DICT.length
  date = $DICT[i][0]
  if date > from and date <= to
    content = $DICT[i][2]
    if color == false
      puts "#{date} (#{date.strftime('%a')})   #{content}"
    else
      delimiter = ' '
      src = $DICT[i][1]
      if colhash[src] == nil
        colhash[src] = (colhash.size) % 7
      end
      delimiter = "\e[4#{colhash[src]+1}m \e[0m"
      puts "\e[32m#{date}\e[0m (\e[33m#{date.strftime('%a')}\e[0m) #{delimiter} #{content.gsub(/http[:\.\/a-zA-Z0-9\?\=\-]*/, "\e[4;34m\\&\e[0m")}"
    end
  end
end

