#!/bin/bash

usage() {
  cat <<EOM
NAME - choose
  Choose a line uniform randomly

Example
  seq 10 | choose
  choose <file>
EOM
  exit
}

if [ "$1" = "-h" -o "$1" = "--help" ]; then
  usage
fi

cat $@ |
awk "
BEGIN {
  srand($RANDOM)
}
NR==1 {
  line = \$0
  x = rand()
}
NR > 1 {
  z = rand()
  if (z > x) {
    line = \$0
    x = z
  }
}
END {
  print line
}
"
