#!/bin/bash

usage() {
    wrap=cat
    if ( command -v bat >/dev/null ); then
        wrap="bat -l bash --style=plain"
    fi
    cat <<EOM | bash -c "$wrap"
clip - Clipboard Utility for Linux, WSL

SYNOPSIS
    # Set/Copy Text
    $ clip "CLIP THIS TEXT"
    $ echo "CLIP THIS TEXT" | clip   # if stdin provided
    $ clip -i input.txt              # from file

    # Get/Paste Text
    $ clip > out.txt
    $ clip -o                        # force to output (write to stdout)
EOM
}

err() {
    echo "$@" >&2
    exit 1
}

SOURCE=
TEXT=
VERBOSE=0
OUTPUT=

# argparse
while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help )
            usage
            exit
            ;;
        -v | --verbose )
            VERBOSE=1
            shift 1
            ;;
        -i )
            SOURCE=$2
            shift 2
            ;;
        -o )
            OUTPUT=1
            shift 1
            ;;
        * )
            TEXT=$1
            shift
            ;;
    esac
done

# detect clipboard command
COMMANDSET=
if ( command -v xsel >/dev/null ); then
    COMMANDSET=xsel
elif ( command -v clip.exe >/dev/null ); then
    COMMANDSET=clip.exe
else
    err "Not found any commands for Clipboard in this System."
fi

if [ "$VERBOSE" = 1 ]; then
    echo "COMMANDSET=$COMMANDSET" >&2
fi

set_text() {
    TEXT="$1"
    case "$COMMANDSET" in
        "clip.exe" )
            echo "$TEXT" | nkf -c | clip.exe
            ;;
        "xsel" )
            echo "$TEXT" | xsel -bi
            ;;
        * )
            err "Cannot Set-Text for $COMMANDSET"
            ;;
    esac
}

set_text_from_source() {
    SOURCE="$1"
    case "$COMMANDSET" in
        "clip.exe" )
            cat "$SOURCE" | nkf -c | clip.exe
            ;;
        "xsel" )
            cat "$SOURCE" | xsel -bi
            ;;
        * )
            err "Cannot Set-Text-From-Source for $COMMANDSET"
            ;;
    esac
}

get_text() {
    case "$COMMANDSET" in
        "clip.exe" )
            powershell.exe /c "Get-Clipboard -Raw -Format Text -TextFormat UnicodeText" | nkf -d | sed '${/^$/d}' | nkf
            ;;
        "xsel" )
            xsel -bo
            ;;
        * )
            err "Cannot Get-Text for $COMMANDSET"
            ;;
    esac
}

# main
if [ "$OUTPUT" ]; then
    # Get-Clipboard
    get_text
elif [ "$SOURCE" ] || [ "$TEXT" ]; then
    # Set-Clipboard
    if [ "$SOURCE" ]; then
        set_text_from_source "$SOURCE"
    elif [ "$TEXT" ]; then
        set_text "$TEXT"
    else
        err "Not work (SOURCE=$SOURCE, TEXT=$TEXT)"
    fi
elif [ ! -t 0 ]; then
    # Set-Clipboard from stdin
    set_text_from_source /dev/stdin
else
    # Get-Clipboard
    get_text
fi
