#!/bin/bash

TMP_WSL=~/Downloads/clip.txt
if [ -d /mnt/c/Users/cympfh ]; then
    TMP_WIN='C:/Users/cympfh/Downloads/clip.txt'
elif [ -d /mnt/c/Users/cympf ]; then
    TMP_WIN='C:/Users/cympf/Downloads/clip.txt'
else
    exit 2
fi

usage() {
    wrap=cat
    if ( command -v bat >/dev/null ); then
        wrap="bat -l bash --style=plain"
    fi
    cat <<EOM | bash -c "$wrap"
clip - Clipboard Utility for Linux, WSL

Copy:
  cat {file} | clip
  clip -i {file}

Paste:
  clip
  clip -o {file}
EOM
}

err() {
    echo "$@" >&2
    exit 1
}

SOURCE=
TARGET=

# argparse
while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help )
            usage
            exit
            ;;
        -i )
            SOURCE=$2
            shift 2
            ;;
        -o )
            TARGET=$2
            shift 2
            ;;
        * )
            echo "Unknown arg; see --help"
            exit 1
            ;;
    esac
done

# detect clipboard command
COMMANDSET=
if ( command -v clip.exe >/dev/null ); then
    COMMANDSET=clip.exe
elif ( command -v xsel >/dev/null ); then
    COMMANDSET=xsel
else
    err "Not found any commands for Clipboard in this System."
fi

copy_text() {
    case "$COMMANDSET" in
        "clip.exe" )
            cat | nkf -s >$TMP_WSL
            powershell.exe /c "Get-Content $TMP_WIN | Set-Clipboard"
            ;;
        "xsel" )
            xsel -bi
            ;;
        * )
            exit 1
            ;;
    esac
}

paste_text() {
    case "$COMMANDSET" in
        "clip.exe" )
            powershell.exe /c "Get-Clipboard -Format Text > $TMP_WIN"
            cat $TMP_WSL | nkf | tr -d '\r'
            ;;
        "xsel" )
            xsel -bo
            ;;
        * )
            exit 1
            ;;
    esac
}

# main
if [ "$TARGET" ]; then
    paste_text > $TARGET
elif [ "$SOURCE" ]; then
    cat $SOURCE | copy_text
elif [ ! -t 0 ]; then
    copy_text
else
    paste_text
fi
