#!/bin/bash

if [ -z "$CODEFORCES_API_KEY" -o -z "$CODEFORCES_API_SECRET" ]; then
    cat <<EOM
Authorization required:
    Get your API key and secret at https://codeforces.com/settings/api
    and export as \$CODEFORCES_API_KEY and \$CODEFORCES_API_SECRET
EOM
fi

#
# Helpers
#

API_ENDPOINT=http://codeforces.com/api/

unixtime() { date "+%s"
}

random-six() {
    (
        if file /dev/urandom >/dev/null; then
            cat /dev/urandom
        else
            cat /dev/random
        fi
    ) | head -c 100 | base64 | head -c 6
}

_sha512() {
    (
        if which shasum >/dev/null 2>/dev/null; then
            shasum -a 512
        elif which sha512sum; then
            sha512sum
        else
            echo "No hash (sha512) command found" >&2
            exit 2
        fi
    ) | sed 's/^\([0-9a-f]*\)\(.*\)/\1/'
}

make-sig() {
    params=$1
    salt="$(random-six)"
    hash="$(echo "$salt/$params#$CODEFORCES_API_SECRET" | _sha512)"
    echo "$salt$hash"
}

make-auth-params() {
    params="$1"
    params="apikey=$CODEFORCES_API_KEY&time=$(unixtime)&$params"
    sig="$(make-sig "$params")"
    echo "$params&apiSig=$sig"
}

request-get() {
    method=$1
    params="$( make-auth-params "$2" )"
    curl "$API_ENDPOINT/$method?$params"
}

#
# Methods
#

user-rating() {
    HANDLE=$1
    request-get "user.rating" "handle=$HANDLE"
}


#
# Entry
#

usage() {
    cat <<EOM
$ codeforces [subcommand]

SUBCOMMANDs

  user-rating <handle-name>
EOM
    exit
}

if [ $# -eq 0 ]; then
    usage
fi

case "$1" in

    user-rating )
        user-rating "$2"
        ;;

    -h | --help )
        usage
        ;;

    * )
        echo "Unknown command: $@" >&2
        usage
        ;;

esac
