#!/bin/bash

#
# ref: https://gitmoji.carloscuesta.me/
#

get-icon() {
    cat <<EOM | peco | grep -o ':[^:]*:'
:alien:             Updating code due to external API changes
:arrow_down:        Downgrading dependencies
:arrow_up:          Upgrading ...
:art:               Improving the format/structure of the code
:bookmark:          Releasing / Tagging
:boom:              Introducing breaking changes
:bug:               Fixing a bug
:building_construction: Making architectural changes
:bulb:              Documenting source code
:children_crossing: Improving user experience / usability
:construction:      WIP
:fire:              Removing code or files
:handshake:         Merging
:heavy_minus_sign:  Removing a dependency
:heavy_plus_sign:   Adding ...
:lipstick:          Improving UI
:lock:              Fixing secrity
:loud_sound:        Adding logs
:memo:              Documentation
:mute:              Removing logs
:new:               Adding code or files
:pencil2:           Fixing typos
:recycle:           Refactoring
:rocket:            Improving performance
:sparkles:          New features
:speech_balloon:    Updating text and literals
:tada:              Initial commit
:truck:             Moving or renaming files
:white_check_mark:  Adding tests
:wrench:            Changing configuration
EOM
}

get-memo() {
    read m; echo $m
}

ICON=$(get-icon)
echo -n "${ICON} {message} > " >&2
read MEMO
echo "$ICON $MEMO" | sed 's/ *$//g'
