#!/bin/bash

usage() {
    cat <<EOM
Usage: empty-gpu-device

  Find most empty gpu devices.
  If multiple device found, choose one randomly.
EOM
}

while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help )
            usage
            exit
            ;;
        * )
            shift
            ;;
    esac
done

if which nvidia-smi >/dev/null; then
    nvidia-smi |
      awk '/Default/ {print $9}' |
      tr -cd '[0-9\n]' |
      cat -n |
      shuf |
      awk 'BEGIN { id=-1; minval = 1000000000 }
          {if($2 < minval) {id = $1 - 1; minval = $2}}
          END { print id }'
else
    echo -1  # dummy
fi
