#!/bin/bash

usage() {
    cat <<EOM
Usage: empty-gpu-device [<NUM>=1]

  Find most empty gpu devices.
EOM
}

NUM=1

while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help )
            usage
            exit
            ;;
        * )
            NUM=$1
            shift
            ;;
    esac
done

if which nvidia-smi >/dev/null; then
    nvidia-smi | grep Default | awk '{print $9}' | cat -n | sed 's/.iB$//g' | sort -n -k 2 |
    head -n $NUM |
    awk '{print $1 - 1}' |
    tr '\n' ',' | sed 's/,$/\n/g'
else
    echo 0  # dummy
fi
