#!/bin/bash

TMP=/tmp/esh

if [ -z "$EDITOR" ] || [ -z "$SHELL" ]; then
  echo "esh error: EDITOR or SHELL is not set."
  exit 2
fi

if [ ! -t 0 ]; then
  cat >$TMP
elif [ $# -gt 0 ]; then
  echo "$@" >$TMP
else
  : >$TMP
fi

$EDITOR $TMP
$SHELL $TMP
