#!/usr/bin/env ruby

require 'time'

def usage
  puts <<EOM
NAME - gdate
  General date

SYSNOPSIS
  gdate <datetime>
    datetime can be either <iso8601>, <rfc2822> or <epoch (unix) time>.
    gdate shows the datetime of it in 3 formats.

TIME FORMAT
  iso8601
    YYYY-MM-DD
    YYYY-MM-DDThh:mm:ss+09:00
  rfc2822
    Mon, 22 Jun 2020 00:00:00 +0000
  epoch time
    Seconds from 1970-01-01T00:00:00Z
EOM
end

def intish(n)
  if n == n.to_i.to_s
    n.to_i
  else
    nil
  end
end

def main(time)
  begin
    if intish(time)
      t = Time.at(intish(time)).to_datetime
    else
      t = DateTime.parse time
    end
    puts t.iso8601
    puts t.rfc2822
    p t.to_time.to_i
  rescue
    STDERR.puts "Unknown datetime format: #{time}"
    exit 1
  end
end

if ARGV.size == 1 and ARGV[0] != '-h' and ARGV[0] != '--help'
  main ARGV[0]
else
  usage
end
