#!/bin/bash

random-source() {
    if file /dev/urandom >/dev/null; then
        cat /dev/urandom
    else
        cat /dev/random
    fi
}

random-source |
head -c 100 |
base64 |
tr '/=' '_@' |
grep -o . |
shuf |
tr -d '\n'

echo
