#!/bin/bash

if [ $# -ne 1 ]; then
  echo "SYNOPSIS: ichigo <html-file-name>"
  echo "  If the file not exists, copy the current thread"
  echo "  Else, append the current thread"
  echo "  To stdout, specific - for filename"
  echo "SYNOPSIS: ichigo --img"
  echo "  stdout image urls in the current thread"
  exit 0
fi

IMGMODE=0 # default
if [ $1 == '--img' ]; then
  IMGMODE=1
fi
OUT=$1

# name of the board (perfect match)
BDNAME='ニュー速VIP'

# name of the thread (perfect match)
THNAME='苺ましまろ'

# get board url ('http://viper.2ch.net/news4vip')
BD=`curl -s http://menu.2ch.net/bbsmenu.html | nkf | grep ">${BDNAME}<" | sed 's/^.*HREF=\([^>]*\).*$/\1/'`
echo BD $BD >&2 # http://viper.2ch.net/news4vip/
if [ _$BD == _ ]; then
  echo "Err BD" >&2
  exit 1
fi

DOM=`echo $BD | cut -d '/' -f 3` ## viper.2ch.net
BID=`echo $BD | cut -d '/' -f 4` ## news4vip
echo DOM $DOM >&2
echo BID $BID >&2

echo ${BD}/subject.txt
TID=`curl -s ${BD}/subject.txt | nkf | grep "<>${THNAME} " | cut -d'<' -f1 | cut -d '.' -f1`
echo TID $TID >&2

if [ _$TID == _ ]; then
  echo "Err TID" >&2
  exit 1
fi

# get thread text
echo http://${DOM}/test/read.cgi/${BID}/${TID} >&2

THREAD=`mktemp`
curl -s http://${DOM}/test/read.cgi/${BID}/${TID} | nkf > $THREAD

if [ $IMGMODE -eq 1 ]; then
  cat $THREAD | grep -o -e "http:[a-zA-Z0-9/.-]*jpg\|http:[a-zA-Z0-9/.-]*gif"
else
  TMP=`mktemp`
  if [ -f $OUT ] && [ $OUT != '-' ]; then
    :
  else

    # header
  cat << EOM > $TMP
<!DOCTYPE html>
<html><head><title>苺ましまろ</title>
<style>
body {
  font-family: "YukarryAA";
}
img {
  height: 25vw;
}
b {
  display: none;
}
</style>
<script>
document.addEventListener("DOMContentLoaded", function(eve) {
  var ls = document.links;
  for (var i=0; i < ls.length; ++i) {
    if (ls[i].href.indexOf('http://jump.2ch.net/?') == 0) {
      var src = ls[i].href.replace('jump.2ch.net/?', '');
      ls[i].href = src;
      ls[i].innerHTML = '<img src=' + src + ' />';
    }
  }
}, false);
</script>
  </head>
  <body>
EOM

    if [ $OUT == '-' ]; then
      cat $TMP
    else
      cp $TMP $OUT
    fi
  fi

  # filter posts html
  cat $THREAD | grep '^<dt' | ruby -n -e 'date = $_.match(/[0-9]{4}\/[0-9]{2}\/[0-9]{2}/); time = $_.match(/[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}/); puts "<!-- #{date} #{time} --> #{$_}"' | sort -k 2,3 > $TMP
  if [ $OUT == '-' ]; then
    cat $TMP
  else
    cat $TMP >> $OUT

    # unique processing
    TMP1=`mktemp`
    cat $OUT | grep '^<!--' | sort -k2,3 -u > $TMP1
    TMP2=`mktemp`
    cat $OUT | grep -v '^<!--' > $TMP2
    cat $TMP2 $TMP1 > $OUT
    rm $TMP1 $TMP2
  fi
  rm $TMP

fi

rm $THREAD
