#!/bin/bash

usage() {
    cat <<EOM
USAGE
    ichigo [options]

OPTIONS
    --img    images only
EOM
    exit
}

## parse args

IMG=0

while [ $# -gt 0 ]; do
    case $1 in
        --img )
            IMG=1
            shift
            ;;
        * )
            usage
            ;;
    esac
done

MENU_URL=http://menu.2ch.net/bbsmenu.html
BDNAME="ニュー速VIP"
THNAME="苺ましまろ"

# get board url (https://*.2ch.net/news4vip/)
BD_URL=$(curl -s $MENU_URL | nkf | grep ">${BDNAME}<" | sed 's/^.*HREF=\([^>]*\).*$/\1/')

DOM=$(echo "$BD_URL" | cut -d '/' -f 3) ## *.2ch.net
BID=$(echo "$BD_URL" | cut -d '/' -f 4) ## news4vip

# get thread url
SUBJECT_URL="${BD_URL}subject.txt"
TID=$(curl -s "$SUBJECT_URL" | nkf | grep "<>${THNAME} " | cut -d'<' -f1 | cut -d '.' -f1)
TH_URL="http://${DOM}/test/read.cgi/${BID}/${TID}"

# read
TMP=$(mktemp)
curl -sL "$TH_URL" | nkf > "$TMP"

if [ $IMG -eq 1 ]; then
    grep -o -e "http:[a-zA-Z0-9/.-]*\(jpg\|jpeg\|gif\)" "$TMP"
    exit 0
fi

html-trim() {
    sed 's,<div>,,g; s,</div>,,g; s,<span>,,g; s,</span>,,g' |
    sed 's,<br>,\n,g' |
    sed 's/<a href[^>]*>//g; s,</a>,,g'
}

html-unescape() {
    sed 's/&gt;/>/g; s/&lt;/</g; s/&quot;/"/g'
}

cat "$TMP" |
sed 's/<div class="post"/\n&/g' | grep '^<div class="post"' | sed 's/<div class="push".*//g' |
sed 's,<div class="post" id="\([0-9]*\)" data-date="[0-9]*" data-userid="ID:\([^"]*\)" data-id="[0-9]*"><div class="meta"><span class="number">[0-9]*</span><span class="name"><b>.*</b></span><span class="date">\([^<]*\)</span><span class="uid">ID:[^<]*</span></div><div class="message"><span class="escaped">,\1@\2 [\3]\n,g' |
html-trim |
html-unescape

rm $TMP
