#!/bin/bash

fetch() {
    curl -s http://www.hinode-hinoiri.com/131016.html |
    grep strong | sed 's/<[^>]*>//g; s/時/ /g; s/分//g' |
    head -n 2 | tr '\n' ' '
}

now() {
    date "+%H %M"
}

calc() {
    t1="$1"  # sunrise
    t2="$2"  # sunset
    t0="$3"  # current
    DAY=1440

    if [ $t1 -le $t0 -a $t0 -lt $t2 ]; then
        i=$(( 1 + 12 * ( t0 - t1 ) / ( t2 - t1 ) ))
        cat <<EOM | head -n $i | tail -1
明六つ
明六つ半
明五つ
明五つ半
明四つ
明四つ半
明九つ
明九つ半
明ハつ
明ハつ半
明七つ
明七つ半
EOM

    else
        i=$(( 1 + 12 * ( ( t0 - t2 + DAY ) % DAY ) / ( ( t1 - t2 + DAY ) % DAY ) ))
        cat <<EOM | head -n $i | tail -1
暮六つ
暮六つ半
暮五つ
暮五つ半
暮四つ
暮四つ半
暮九つ
暮九つ半
暮ハつ
暮ハつ半
暮七つ
暮七つ半
EOM
    fi

}

minutes() {
    t1="$1"  # sunrise
    t2="$2"  # sunset
    t0="$3"  # current
    DAY=1440

    if [ $t1 -le $t0 -a $t0 -lt $t2 ]; then
        echo $(( ( 60 * 12 * ( t0 - t1 ) / ( t2 - t1 ) ) % 60 ))
    else
        echo $(( ( 60 * 12 * ( ( t0 - t2 + DAY ) % DAY ) / ( ( t1 - t2 + DAY ) % DAY ) ) % 60 ))
    fi
}

debug() {
    echo "Debug:"
    echo "Sunrise 6:00"
    echo "Sunset 18:10"
    t1=$(( 6 * 60 ))
    t2=$(( 18 * 60 + 10 ))
    for h in $(seq 0 23); do
        for m in $(seq 0 5 59); do
            echo -n "${h}:${m} "
            t0=$(( h * 60 + m ))
            calc $t1 $t2 $t0 | tr '\n' ' '
            minutes $t1 $t2 $t0
        done
    done
}

if [ "$1" = "debug" ]; then
    debug
    exit
fi

fetch | (
    read h1 m1 h2 m2
    t1=$((h1 * 60 + m1))
    t2=$((h2 * 60 + m2))
    now | (
        read h0 m0
        t0=$((h0 * 60 + m0))
        calc $t1 $t2 $t0 | tr '\n' ' '
        minutes $t1 $t2 $t0 | sed 's/.*/&分/g'
    )
)
