#!/bin/bash

fetch() {
    curl -s http://www.hinode-hinoiri.com/131016.html |
    grep strong | sed 's/<[^>]*>//g; s/時/ /g; s/分//g' |
    head -n 2 | tr '\n' ' '
}

now() {
    date "+%H %M"
}

calc() {
    t1="$1"  # sunrise
    t2="$2"  # sunset
    t0="$3"  # current
    NOON=720
    DAY=1440

    if [ $t0 -lt $t1 ]; then
        i=$(( 1 + t0 * 6 / t1 ))
        cat <<EOM | head -n $i | tail -1
暮九つ
暮九つ半
暮ハつ
暮ハつ半
暮七つ
暮七つ半
EOM

    elif [ $t0 -lt $NOON ]; then
        i=$(( 1 + 6 * ( t0 - t1 ) / ( NOON - t1 ) ))
        cat <<EOM | head -n $i | tail -1
明六つ
明六つ半
明五つ
明五つ半
明四つ
明四つ半
EOM

    elif [ $t0 -lt $t2 ]; then
        i=$(( 1 + 6 * ( t0 - NOON ) / ( t2 - NOON ) ))
        cat <<EOM | head -n $i | tail -1
明九つ
明九つ半
明ハつ
明ハつ半
明七つ
明七つ半
EOM

    else
        i=$(( 1 + 6 * ( t0 - t2 ) / ( DAY - t2 ) ))
        cat <<EOM | head -n $i | tail -1
暮六つ
暮六つ半
暮五つ
暮五つ半
暮四つ
暮四つ半
EOM

    fi

}

fetch | (
    read h1 m1 h2 m2
    t1=$((h1 * 60 + m1))
    t2=$((h2 * 60 + m2))
    now | (
        read h0 m0
        t0=$((h0 * 60 + m0))
        calc $t1 $t2 $t0
    )
)
