#!/bin/bash

usage() {
    cat << EOM
Usage: kindle [-S <name>] [--convert] <pdf-url>
EOM
    exit 0
}

unwords() {
    echo "$@" | tr ' ' '_'
}

if [ $# -eq 0 -o "_$1" = "_-h" -o "_$1" = "_--help" ]; then
    usage
fi

TO=cympfh_40@kindle.com
DIR=$(mktemp -d)
rm -rf "$DIR"
mkdir "$DIR"

# argparse
OUTPUT="--trust-server-names"
SUBJECT=""
TARGET=""

while [ "_$1" != "_" ]; do
    case $1 in

        # pdf name
        -s | -S )
            S=$(unwords "$2")
            case $S in
                *.pdf )
                    OUTPUT="-O $DIR/$S"
                    ;;
                * )
                    OUTPUT="-O $DIR/$S.pdf"
                    ;;
            esac
            shift
            shift
            ;;

        # convert to .azw
        --convert | -C )
            SUBJECT=convert
            shift
            ;;

        * )
            TARGET=$1
            shift
    esac
done

# parse target
case $TARGET in
    http* )
        # fetch
        URL=$TARGET
        echo "download from $URL"
        UA='Mozilla/5.0 (X11; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0'
        wget -P "$DIR" -U "$UA" $OUTPUT "$URL"
        for f in $DIR/*.pdf; do
            TARGET=$f
            break
        done
        ;;
    * )
        ;;
esac

# sendmail
echo "sending $TARGET"
mutt -s "$SUBJECT" "$TO" -a "$TARGET" <<< "Ok, Amazon"

rm -rf "$DIR"
