#!/bin/bash

usage() {
    cat << EOM
Usage: kindle [-S <name>] <pdf-url>
EOM
    exit 0
}

if [ $# -eq 0 -o "_$1" = "_-h" -o "_$1" = "_--help" ]; then
    usage
fi

TO=cympfh_40@kindle.com
DIR=`mktemp -d`
rm -rf $DIR
mkdir $DIR

# argparse
OUTPUT="--trust-server-names"
if [ "_$1" = "_-S" ]; then
    case $2 in
        *.pdf )
            OUTPUT="-O $DIR/$2"
            ;;
        * )
            OUTPUT="-O $DIR/$2.pdf"
            ;;
    esac
    shift
    shift
fi

# fetch
URL=$1
echo "download from $URL"
UA='Mozilla/5.0 (X11; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0'
wget -P "$DIR" -U "$UA" $OUTPUT $URL

# sendmail
for f in $DIR/*.pdf; do
    echo "sending $f"
    mutt -s "" "$TO" -a "$f" <<< "Ok, Amazon"
    break
done

rm -rf $DIR
