#!/bin/bash

POD_NAME_EXP=
CONTAINER_NAME=
TAIL_NUM=10000
LOG_FILTERING=

usage() {
    cat <<EOM
SYNOPSIS
    kubelogs
        --pod "HOGE-.*-WEB"          # awk regexp matching
        -c \$CONTAINER_NAME           # exact name (if need)
        -n 2000                      # num for --tail
        --log "grep -v '200 GET'"    # log filtering command (optional)
EOM
}

pod_filter() {
    awk "\$1 ~ /$POD_NAME_EXP/"
}

pods() {
    kubectl get pods | pod_filter | awk '$0=$1'
}

logs() {
    if [ "$CONTAINER_NAME" ]; then
        kubectl logs "$1" -c "$CONTAINER_NAME" --tail $TAIL_NUM
    else
        kubectl logs "$1" --tail $TAIL_NUM
    fi
}

log_filter() {
    if [ "$LOG_FILTERING" ]; then
        bash -c "$LOG_FILTERING"
    else
        cat
    fi
}

# argparse
while [ $# -gt 0 ]; do
    case "$1" in
        --help | -h | help | -? | ? )
            usage
            exit
            ;;
        --pod | -p | -P )
            POD_NAME_EXP=$2
            shift 2
            ;;
        -c | -C )
            CONTAINER_NAME=$2
            shift 2
            ;;
        -n | -N )
            TAIL_NUM=$2
            shift 2
            ;;
        --log | -l | -L )
            LOG_FILTERING=$2
            shift 2
            ;;
        * )
            echo "Unknown Option: $1" >&2
            exit 1
            ;;
    esac
done

if [ ! "$POD_NAME_EXP" ]; then
    echo "--pod must be passed" >&2
    exit 1
fi

for pod in $(pods); do
    printf "\e[32mChecking $pod\e[0m\n"
    logs $pod | log_filter
done
