#!/bin/bash

for dep in docker; do
    if ! which $dep >/dev/null; then
        echo "$dep required"
        exit 1
    fi
done

usage() {
    echo "Usage: latex <file.tex>"
    exit
}

if [ $# -ne 1 ]; then
    usage
fi

FILENAME=$1
BASENAME=${FILENAME%.tex}
BASENAME=${BASENAME%.md}
BASENAME=${BASENAME%.mkd}

case "$1" in
    *.md | *.mkd )
        pandoc -s $1 -o $BASENAME.tex -V documentclass=bxjsarticle -V classoption=pandoc -V classoption=jafont=ipaex
        ;;
esac

docker run --rm -v ${PWD}:/workdir paperist/alpine-texlive-ja uplatex $BASENAME.tex
docker run --rm -v ${PWD}:/workdir paperist/alpine-texlive-ja dvipdfmx $BASENAME
