#!/bin/bash

# depends on
# git@github.com:eBrnd/i3lock-color.git (this is obsolete)
# https://github.com/chrjguill/i3lock-color

IMAGE=/tmp/i3lock.png
MASCOT=$(dirname $0)/img/azusa.png

import -window root $IMAGE
# convert $IMAGE -noise 7 +noise Uniform -gaussian-blur 3x3 -colors 10 - | composite -gravity southeast $MASCOT - $IMAGE
convert $IMAGE -threshold 30% -modulate 20 - | composite -gravity southeast $MASCOT - $IMAGE
i3lock \
    --textcolor=00000000 \
    --insidecolor=00000000 \
    --insidevercolor=00000000 \
    --insidewrongcolor=00000000 \
    --ringcolor=ffffff30 \
    --ringvercolor=ffff0030 \
    --ringwrongcolor=ff000030 \
    --linecolor=00000000 \
    --keyhlcolor=ffffffff \
    -i $IMAGE

rm $IMAGE
