#!/bin/bash

usage() {
    cat <<USAGE
next -- normalize extension

Usage: next file [file...]
USAGE
    exit 0
}

if [ $# -eq 0 ]; then
    usage
fi

for f in $@; do
    base=${f%.*}
    ext=_

    kind=$(file -- "$f" | awk '{print $2}')
    case $kind in
        JPEG )
            ext=jpg
            ;;
        GIF )
            ext=gif
            ;;
        PNG )
            ext=png
            ;;
    esac

    if [ "$ext" = _ ]; then
        echo "Unknown extension: $f" >&2
    else
        echo "$f was moved to $base.$ext" >&2
        mv -- "$f" "$base.$ext"
    fi

done
