#!/bin/bash

TITLE=
SUBTITLE=
MESSAGE=
ICON=$HOME/bin/img/osaka.jpg
SOUND=0

usage() {
  cat << USAGE
NAME
    notify -- my wrapper for notify-send (ubuntu), terminal-notifier (OSX)

SYNOPSIS
    notify [ --title <string> ] [ --subtitle <string> ] [ --icon <path or URL> ] [ --sound ] <string>
USAGE
  exit 0
}

nopackage() {
    echo "Please install notify-send or terminal-notifier. Or implement"
    exit 1
}

# args
while [ -n "$1" ]; do
    case $1 in
        --title | -title )
            TITLE=$2
            shift 2
            ;;
        --subtitle | --sub | -subtitle | -sub )
            SUBTITLE=$2
            shift 2
            ;;
        --icon | -icon )
            ICON=$2
            shift 2
            ;;
        --help | -h )
            usage
            ;;
        --sound | -S )
            SOUND=1
            shift
            ;;
        * )
            MESSAGE=$1
            shift 1
            ;;
    esac
done

# exec notify
if command -v terminal-notifier >/dev/null; then
    terminal-notifier -title "${TITLE}" -subtitle "${SUBTITLE}" -message "${MESSAGE}" -appIcon "${ICON}"
elif command -v notify-send >/dev/null; then
    if [ -n "${SUBTITLE}" ]; then
        TITLE="${TITLE} - ${SUBTITLE}"
    fi
    if [ -z "${TITLE}" ]; then
        TITLE="notification"
    fi
    notify-send "${TITLE}" "${MESSAGE}" --icon "${ICON}"
else
    nopackage
fi

# --sound
if [ $SOUND -eq 1 ]; then
    SND_PATH=/tmp/notification.sound.mp3
    if [ ! -f $SND_PATH ]; then
        wget -O $SND_PATH https://notificationsounds.com/soundfiles/a86c450b76fb8c371afead6410d55534/file-sounds-1108-slow-spring-board.mp3
    fi
    mplayer -quiet $SND_PATH >/dev/null 2>&1 &
fi
