#!/bin/bash

URL=$1

TMP=$(mktemp)
curl -sL "$URL" >$TMP
TITLE=$(cat $TMP | web-grep "<meta property=og:title content={}>" | tr -d '"\n')
IM=$(cat $TMP | web-grep "<meta property=og:image content={}>" | tr -d '"\n')
DESC=$(cat $TMP | web-grep "<meta property=og:description content={}>" | tr -d '"\n')

qj -e ".url=$URL" \
   -e ".og.title=$TITLE" \
   -e ".og.image=$IM" \
   -e ".og.description=$DESC"

rm $TMP
