#!/usr/bin/env python

import openai
import os
import click


class TUI:
    @staticmethod
    def get_input(prompt: str) -> str | None:
        header = f"% {prompt}"
        buffer: str = click.edit(f"{header}\n\n")  # type: ignore
        if not buffer:
            return None
        lines = buffer.split("\n")
        if lines[0] == header:
            lines = lines[1:]
        return " ".join(line for line in lines if line).strip()

    @staticmethod
    def hr():
        click.secho("---", fg="yellow")

    @staticmethod
    def write(label: str, text: str, labelcolor: str, hr: bool = True):
        click.secho(f"[{label}] ", nl=False, fg=labelcolor)
        click.echo(text)
        if hr:
            TUI.hr()


class ChatGPT:
    SYSTEM_PROMPT = """
ユーザーと一緒に論文を読み進めていき あなたは内容を的確に要約したものを出力する
要約は簡潔に箇条書きに日本語で.
ただし登場する術語 (technical term) は無理に和訳せず そのまま英語のまま使ってよい
"""

    def __init__(self, title: str, abst: str):
        self.client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

        self.messages = [
            {"role": "system", "content": self.SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"""
今から "{title}" というタイトルの論文を読む
論文の概要を以下に示す
まず論文の全体像を把握して要約してください

---
{abst}
---
""",
            },
        ]
        result = self.client.chat.completions.create(
            model="gpt-4-0125-preview",
            messages=self.messages,  # type: ignore
        )
        self.abst = result.choices[0].message.content
        self.messages = [
            {"role": "system", "content": self.SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"""
今から "{title}" というタイトルの論文を読みます
この論文の概要を次に示すので参考にしてください

---
{self.abst}
---

次に私は論文の断片をコピペするので あなたはその内容を簡潔に要約して出力してください
""",
            },
        ]

    def summarize(self, text: str) -> str | None:
        self.messages.append(
            {
                "role": "user",
                "content": f"""
論文の断片:
---
{text}
---
""",
            }
        )
        result = self.client.chat.completions.create(
            model="gpt-4-1106-preview",
            messages=self.messages,  # type: ignore
        )
        self.messages.pop()
        return result.choices[0].message.content


@click.command()
def main():
    title = TUI.get_input("Title")
    if not title:
        return
    TUI.write("TITLE", title, "green", hr=True)

    abst = TUI.get_input("Abstract")
    if not abst:
        return

    gpt = ChatGPT(title, abst)
    if gpt.abst:
        TUI.write("ABST", gpt.abst, "blue", hr=True)

    while click.confirm("next?", default=None):
        text = TUI.get_input("Text")
        if not text:
            break
        TUI.write("TEXT", text, "green", hr=False)

        summary = gpt.summarize(text)
        if not summary:
            summary = "{Error: ChatGPT response is empty}"
        TUI.write("SUMMARY", summary, "blue", hr=True)


if __name__ == "__main__":
    main()
