#!/bin/bash

usage() {
    cat <<EOM
NAME
  pbpaste-stream -- clipboard stream

SYNOPSIS
  pbpaste-stream [-0]

OPTIONS
  -0     include the clipboard on starting command (exclude in default)
EOM
exit
}

paste() {
    if [ "$(uname)" = "Darwin" ]; then
        pbpaste
    else
        xsel -bo
    fi
}

hash() {
    if [ "$(uname)" = "Darwin" ]; then
        md5
    else
        md5sum
    fi
}

ZERO=0

if [ $# -eq 1 ]; then
    case "$1" in
        -h | -help | --help )
            usage
            ;;
        -0 )
            ZERO=1
            ;;
        * )
            usage
    esac
fi

LAST=$(paste)
LAST_HASH=$(echo "$LAST" | hash)
if [ $ZERO -eq 1 ]; then
    echo "$LAST"
fi

while :; do
    LINE=$(paste)
    LINE_HASH=$(echo "$LINE" | hash)
    if [ "$LAST_HASH" != "$LINE_HASH" ]; then
        echo "$LINE"
        LAST_HASH=$LINE_HASH
    fi
    sleep 1
done
