#!/usr/bin/env python

import itertools
import sys
import click
import pypinyin


@click.command()
@click.argument("text", type=str, required=False)
def main(text: str):
    """\b
    SYNOPSIS
        pinyin "中心"
        echo "中心" | pinyin
    """
    if not text:
        text = sys.stdin.read()

    res = pypinyin.pinyin(text)
    for ws in itertools.product(*res):
        print("".join(ws))


if __name__ == "__main__":
    main()
