#!/bin/bash

usage() {
  cat << HELP
NAME
    pixiv-dl -- pixiv-dl

SYNOPSIS
    pixiv-dl <PHPSESSID> <URL>
HELP
  exit 0
}


if [ $# -ne 2 ]; then
    usage
fi

PHPSESSID=$1
URL=$2

case $URL in

  *manga* )
    curl -s "$URL" -H "Cookie: PHPSESSID=$PHPSESSID; p_ab_id=0;" |
    sed 's/<img/\n<>/g' |
    grep -e '^<>' |
    grep ui-scroll-view |
    sed 's/^.*data-src=\"\([^\"]*\)\".*$/\1/' |
    xargs -n 1 wget --referer="$URL"
    ;;

  *medium* )
    curl -s "$URL" -H "Cookie: PHPSESSID=$PHPSESSID; p_ab_id=0;" |
    sed 's/<img/\n<>/g' |
    grep -e '^<>' |
    grep original-image |
    sed 's/^.*data-src=\"\([^\"]*\)\".*$/\1/' |
    xargs -n 1 wget --referer="$URL"
    ;;

  * ) echo 'unknown URL'
    ;;
esac
