#!/bin/bash

URL=$1
case $URL in

  *manga* )
    curl -s "$URL" -H 'Cookie: PHPSESSID=4452325_1a94695c594dc91edf46ef6a88585b96; p_ab_id=0;' |
    sed 's/<img/\n<>/g' |
    grep -e '^<>' |
    grep ui-scroll-view |
    sed 's/^.*data-src=\"\([^\"]*\)\".*$/\1/' |
    xargs -n 1 wget --referer="$URL"
    ;;

  *medium* )
    curl -s "$URL" -H 'Cookie: PHPSESSID=4452325_1a94695c594dc91edf46ef6a88585b96; p_ab_id=0;' |
    sed 's/<img/\n<>/g' |
    grep -e '^<>' |
    grep original-image |
    sed 's/^.*data-src=\"\([^\"]*\)\".*$/\1/' |
    xargs -n 1 wget --referer="$URL"
    ;;

  * ) echo 'unknown URL'
    ;;
esac
