#!/bin/bash

usage() {
    cat <<EOM
NAME
  pwait - wait processes based on name

SYNOPSIS
  pwait [options] pattern

OPTIONS
  -n <int>   check times
  -i <int>   interval (second)
EOM
    exit 0
}

N=5
I=5
pattern=


## parse args
while [ "_$1" != "_" ]; do
    case "$1" in
        -h | --help )
            usage
            ;;
        -n )
            N=$2
            shift 2
            ;;
        -i )
            I=$2
            shift 2
            ;;
        * )
            pattern=$1
            shift
            ;;
    esac
done

if [ "_$pattern" == "_" ]; then
    usage
fi

for _ in $(seq "$N"); do
    while :; do
        sleep "$I"
        pgrep "$pattern" >/dev/null || break
    done
done
