#!/bin/bash

if [ $# -ne 1 ]; then
  cat << HELP
NAME
  ren -- rename

SYNOPSYS
  ren <file>
HELP
  exit 0
fi

which md5sum > /dev/null
if [ $? = 0 ]; then
  HASH=`md5sum "$1" | cut -d ' ' -f1`
else
  HASH=`md5 "$1" |awk '{print $NF}'`
fi

EXT=${1##*.}
if [ "_${EXT}" = "_${1}" ]; then # no extension?
  echo ${HASH}
  mv "$1" ${HASH}
else
  echo ${HASH}.${EXT}
  mv "$1" ${HASH}.${EXT}
fi
