#!/bin/bash

if [ $# -ne 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
  cat << USAGE
SYNOPSIS: $0 <seiga-story-page (/watch/mgXXXXXX)>
USAGE
  exit 0
fi

URL="$1"
FIRSTPAGE=$( curl -s "$URL" | grep 'img.*class.*thumb' | grep -o 'src="[^"]*"' | tr -d -c 0-9 )
# FIRSTPAGE=5709493 for http://lohas.nicoseiga.jp//thumb/5709493p

run() {
  URL="http://lohas.nicoseiga.jp//thumb/${1}p"
  echo "$URL"
  wget "$URL" && run $(( $1 + 1 ))
}

run "$FIRSTPAGE"
