#!/bin/bash

usage() {
    cat <<EOM
SYSNOSIS
  shindan [OPTIONS] <SHINDAN-ID>

ARGS
  SHINDAN-ID         https://shindanmaker.com/311937 -> 311937

OPTIONS
  --name <NAME>      Your Name for Shindan. By default, random string will be used.
  --text             Trim Hashtag and URL
EOM
    exit
}

ID=
USERNAME=$(( RANDOM ))
TRIM=0

while [ $# -gt 0 ]; do
    case "$1" in
        --name )
            USERNAME=$2
            shift 2
            ;;
        --text )
            TRIM=1
            shift
            ;;
        * )
            ID=$1
            shift
            ;;
    esac
done

if [ -z "$ID" ]; then
    usage
fi

trim-text() {
    if [ $TRIM -eq 0 ]; then
        cat  # Nothing to do
    else
        sed 's/#[a-zA-Z0-9_]*//g' |
        sed 's/http[^ ]*//g'
    fi |
        sed 's/^ *//g' |
        sed 's/ *$//g' |
        awk '$1'  # remove empty lines
}

BUFFER=$(mktemp)

curl -s --dump-header - https://shindanmaker.com/$ID > $BUFFER
SESSION=$( grep -o '_session=[^;]*' $BUFFER )
TOKEN=$( web-grep '<input type="hidden" name="_token" value="{}">' $BUFFER )
curl -sL "https://shindanmaker.com/${ID}" \
    -H "Cookie: ${SESSION}" \
    --data-raw "_token=${TOKEN}&name=${USERNAME}" |
    web-grep '<textarea>{}</textarea>' |
    trim-text

[ -f "${BUFFER}" ] && rm "${BUFFER}"
