#!/bin/bash

usage() {
    cat <<EOM
SYSNOSIS
  shindan <ID> [NAME]

ARGS
  ID         https://shindanmaker.com/311937 -> 311937
  NAME       Your name (optional)
EOM
    exit
}

ID=
USERNAME=$(( RANDOM ))

while [ $# -gt 0 ]; do
    if [ -z "$ID" ]; then
        ID=$1
    else
        USERNAME=$1
    fi
    shift
done

if [ -z "$ID" ]; then
    usage
fi

while-textarea() {
    awk 'BEGIN { v=1 }
/<\/textarea>/ { v=0 }
v { print $0 }'
}

trim() {
    sed 's/^[ \t]*//g' |
    sed 's/<[^>]*>//g' |
    sed '/^$/d'  # empty lines
}

curl -s "https://shindanmaker.com/$ID" -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0' -H 'Content-Type: multipart/form-data; boundary=---------------------------2056919927962200798503755374' --data-binary $'-----------------------------2056919927962200798503755374\r\nContent-Disposition: form-data; name="u"\r\n\r\n'$USERNAME$'\r\n-----------------------------2056919927962200798503755374--\r\n' |
grep -A 10 '<textarea id="modaltweet"' |
while-textarea |
trim
