#!/bin/bash

OUT=~/Pictures/hoge.png

case "$(uname)" in
  Linux )
    import -density 2000 -depth 900 "$OUT"
    xclip -selection clipboard -t image/png -i "$OUT"
    ;;
  Darwin )
    screencapture -x -s "$OUT"
    ;;
esac
