#!/bin/bash

OUT=~/Pictures/hoge.png
AREA=0  # 0=Fullscreen, 1=Area

while [ $# -gt 0 ]; do
  case "$1" in
    --area | -a | -A )
      AREA=1
      shift
      ;;
    --fullscreen | --full | -f | -F )
      AREA=0
      shift
      ;;
    --out | -o )
      OUT=$2
      shift 2
      ;;
  esac
done

OPTS=
if [ $AREA = 0 ]; then
  :
else
  OPTS="--area"
fi

gnome-screenshot $OPTS -f "$OUT"
xclip -selection clipboard -t image/png -i "$OUT"
