#!/bin/bash

# See: https://github.com/OpenWonderLabs/SwitchBotAPI

usage() {
    cat <<EOM
SYNOPSIS
    $ switchbot devices
        list up devices

    $ switchbot status <DEVICE_ID>
        show status

    $ switchbot send <DEVICE_ID> '<JSON>'
EOM
}

# get /v1.0/<API_URI>
get() {
    curl -sL \
        -H "Authorization: $SWITCHBOT_API_TOKEN" \
        -H "Content-Type: application/json; charset: utf8" \
        "https://api.switch-bot.com$1"
}
post() {
    curl -sL \
        -H "Authorization: $SWITCHBOT_API_TOKEN" \
        -H "Content-Type: application/json; charset: utf8" \
        -XPOST \
        "https://api.switch-bot.com$1" \
        --data "$2"
}

switchbot-devices() {
    get "/v1.0/devices"
}

switchbot-status() {
    get "/v1.0/devices/$1/status"
}

switchbot-send() {
    post /v1.0/devices/$1/commands "$2"
}

if [ $# -eq 0 ]; then
    usage
    exit
fi

case "$1" in
    help | --help )
        usage
        exit
        ;;
    devices | device )
        switchbot-devices
        ;;
    status )
        switchbot-status "$2"
        ;;
    send )
        switchbot-send "$2" "$3"
        ;;
    * )
        echo Unknown subcommand $1
        exit 1
        ;;
esac
