#!/usr/bin/env python3

import qrcode
import click


@click.command()
@click.argument("data")
@click.option("--output", "-o", default="out.png", help="Output file name")
def main(data: str, output: str):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(data)
    qr.make(fit=True)
    qr.make_image(fill_color="black", back_color="white").save(output)


if __name__ == "__main__":
    main()
