#!/bin/bash

U=cympfh
N=5
D=2

usage() {
  cat << USAGE
NAME
  tumblr -- slideshow on my Tumblr

SYNOPSIS
  tumblr [ -u <username> ] [ --pages <int> ] [ -D <int> ]

  -u           Tumblr username (optional, default "$U")
  --pages, -n  The number of pages of rss (optional, default $N)
  -D           Interval (sec) of the slideshow (optional, default $D)
USAGE
  exit 0
}

while [ ! -z "$1" ]; do
  case $1 in
    -n | --pages )
      N="$2"
      shift 2
      ;;
    -D )
      D="$2"
      shift 2
      ;;
    -u )
      U="$2"
      shift 2
      ;;
    * )
      usage
      ;;
  esac
done

getpage() {
  curl -s "$1://${U}.tumblr.com/page/$2/rss" |
    grep -o 'src="[^"][^"]*' | sed 's/^src="//g;s/"$//g'
}

FILELIST=$(mktemp)

for i in $(seq 1 "$N"); do
  echo -ne "\rPage [$i/$N]" >&2
  getpage http "$i" >> "$FILELIST"
  getpage https "$i" >> "$FILELIST"
done
echo

NUM=$(wc -l < "$FILELIST")
echo -e "Found ${NUM} images" >&2

if [ "$NUM" -gt 0 ]; then
  feh -D "$D" -FZz --filelist "$FILELIST"
fi

rm "$FILELIST"
