#!/bin/bash

usage() {
  cat << USAGE
NAME
  tumblr -- slideshow on my Tumblr

SYNOPSIS
  tumblr [ -n <int> ] [ -D <int> ]

  -n  the number of pages of rss
  -D  interval (sec) of the slideshow
USAGE
  exit 0
}

N=3
D=2
while [ ! -z "$1" ]; do
  case $1 in
    -n )
      N="$2"
      shift 2
      ;;
    -D )
      D="$2"
      shift 2
      ;;
    * )
      usage
      ;;
  esac
done

imgs(){
  curl -s "$1" | grep -o 'src="[^"]*"' | sed 's/^src="//g;s/"$//g'
}

feh -D "$D" -FZz $(for i in $(seq 1 "$N"); do imgs "http://cympfh.tumblr.com/page/$i/rss"; done)
