#!/bin/sh

BINS=$( cat << ARRAY
  /usr/libexec/locate.updatedb
  /usr/bin/updatedb
ARRAY
)

for BIN in $BINS; do
  if [ -f $BIN ]; then
    $BIN
    exit 0
  fi
done

echo "Something wrong? Any proper updatedb isnt set"

