#!/bin/bash

usage() {
  echo "url [-e <extension>] <url>" >&2
  exit 1
}

if [ $# == 0 ]; then
  usage
fi

if [ "_$1" == "_-e" ]; then
  EXT=$2
  URL=$3
else
  EXT=${1##*.}
  URL=$1
fi

if [ "_$EXT" == "_" ]; then
  usage
fi
if [ "_$URL" == "_" ]; then
  usage
fi

wget --quiet -O /tmp/$$.$EXT $URL
echo /tmp/$$.$EXT

