#!/usr/bin/env python

import sys
import time
import subprocess

import click
from pythonosc import udp_client


class OSC:
    def __init__(self, verbose: bool, dry_run: bool):
        """初期化

        Parameters
        ----------
        verbose
            冗長モード
        dry_run
            dry-run, 実際には実行しないモード
            verbose モードを自動でオンにする
        """
        self.verbose = verbose or dry_run
        self.dry_run = dry_run
        res = subprocess.run("withcache ipwin", shell=True, capture_output=True)
        ip = res.stdout.decode().strip()
        port = 9000

        if self.verbose:
            click.secho(f"[OSC] UDP to {ip}:{port}", err=True, fg="yellow")
        self.client = udp_client.SimpleUDPClient(ip, port)

    def set_typing(self, indicator: bool):
        """タイピング状態をセットする

        Parameters
        ----------
        indicator
            状態をオンにするかオフにするか
        """
        if self.verbose:
            click.secho(f"[OSC] set_typing {indicator}")
        if not self.dry_run:
            self.client.send_message("/chatbox/typing", indicator)

    def send(self, message: str, notify: bool):
        """送信

        Parameters
        ----------
        message
            テキスト
        notify
            通知音を鳴らすかどうか
        """
        if self.verbose:
            click.secho(f"[OSC] send message={message}, notify={notify}")
        if not self.dry_run:
            self.client.send_message("/chatbox/input", [message, True, notify])


@click.command()
@click.option(
    "--lazy",
    "-L",
    type=int,
    default=0,
    help="入力中状態を何秒作るか. デフォルトでは 0 秒 (作らない)",
)
@click.option("--quiet", "-q", is_flag=True, default=False, help="通知音を消すモード")
@click.option("--verbose", "-v", is_flag=True, default=False, help="冗長モード")
@click.option("--dry-run", "-N", is_flag=True, default=False, help="dry-run")
@click.argument("messages", type=str, nargs=-1)
def main(
    lazy: int,
    quiet: bool,
    verbose: bool,
    dry_run: bool,
    messages: list[str],
):
    text: str
    if not messages:
        text = sys.stdin.read()
    else:
        text = " ".join(messages)

    osc = OSC(verbose, dry_run)
    if lazy > 0:
        if verbose:
            click.secho(f"Sleep {lazy}", err=True, fg="yellow")
        osc.set_typing(True)
        time.sleep(lazy)

    osc.send(text, not quiet)
    if lazy > 0:
        osc.set_typing(False)


if __name__ == "__main__":
    main()
