#!/usr/bin/env python

import time
import click
from pythonosc import udp_client
import subprocess


res = subprocess.run("ipwin", capture_output=True)
ip = res.stdout.decode()
port = 9000


@click.command()
@click.option("--lazy", type=int, default=-1)
@click.argument("messages", type=str, nargs=-1)
def main(lazy: int, messages: list[str]):
    message = " ".join(messages)
    client = udp_client.SimpleUDPClient(ip, port)
    if lazy > 0:
        client.send_message("/chatbox/typing", True)
        time.sleep(lazy)
    client.send_message("/chatbox/input", [message, True, True])


if __name__ == "__main__":
    main()
