#!/bin/bash

usage() {
    cat <<EOM
NAME
    wait-at

    Wait until next time.

SYNOPSIS

    wait-at [OPTIONS] [TIME]

OPTIONS

    -s, --silent

TIME
    "HH:MM" or "HH:MM:SS" (E.g. "19:00", "19:00:30")
EOM
    exit
}

max() {
    (( $1 > $2 )) && echo "$1" || echo "$2"
}

min() {
    (( $1 < $2 )) && echo "$1" || echo "$2"
}

[ $# -eq 0 ] && usage

TIME=
VERBOSE=1

# argparse
while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help )
            usage
            ;;
        -s | --silent )
            VERBOSE=0
            shift
            ;;
        * )
            TIME="$1"
            shift 1
            ;;
    esac
done

# get next time
now=$( date "+%s" )
t=$( date -d "$TIME" "+%s" )
oneday=$(( 24 * 60 * 60 ))

t=$(( t - oneday ))
while (( t < now )); do
    t=$(( t + oneday ))
done

if [ $VERBOSE -eq 1 ]; then
    echo "waiting: $(date -d "@$t") (UNIX_TIME=$t)" >&2
fi

# sleep loop
while :; do
    now=$( date "+%s" )
    (( now >= t )) && break
    dt=$(max 1 $(( t - now - 3 )) )
    dt=$(min $dt 3600)
    sleep "$dt"
done
