#!/bin/bash

mkdir -p /tmp/withcache
CACHEDIR=/tmp/withcache

usage() {
  cat <<EOM
NAME - withcache

SYNOPSIS
  withcache [OPTION] [COMMAND...]

  withcache curl http://hoge.com/
    Run naiive and cache the result (only stdout)
  withcache curl http://hoge.com/
    Return its cache

OPTION
  --ttl, -t <caching time seconds>
    default ttl is 3600 (=1hr).
    NOTE:
      -t 0: zero ttl (clear cache immediately)
      -t -1: infinity ttl (use cache always)
EOM
}

TTL=3600

# argparse
case "$1" in
  -h | --help )
    usage
    exit
    ;;
  --ttl | -t )
    TTL=$2
    shift 2
    ;;
  * )
    ;;
esac

HASHKEY="$(echo "$@" | base64)"
HASHFILE="$CACHEDIR/$HASHKEY"

# cache hit check
HIT=
if [ -f "$HASHFILE" ]; then
  if [ "$TTL" -eq 0 ]; then
    HIT=0
  elif [ "$TTL" = "-1" ]; then
    HIT=1
  elif [[ $(date -r "$HASHFILE" +%s) -ge $(( $(date +%s) - $TTL )) ]]; then
    HIT=1
  else
    HIT=0
  fi
else
  HIT=0
fi

if [ "$HIT" -eq 1 ]; then
  cat "$HASHFILE"
else
  $@ | tee "$HASHFILE"
fi
