#!/usr/bin/env ruby
# coding: utf-8

def usage
  puts <<EOM
SYNOPSIS:
  xbacklight [ -display <display> ] = <brightness>
  xbacklight [ -display <display> ] + <brightness-diff>
  xbacklight [ -display <display> ] - <brightness-diff>

NOTE:
  This brightness be specified by Int in 0-100, or Float in 0.0-1.0
EOM
  exit 0
end

def clip(x, sub, sup)
  [sub, [sup, x].min].max
end

def update(display, brightness)
  brightness = clip(brightness, 0.01, 1.0)
  puts "set #{display} brightness = #{brightness}"
  `xrandr --output #{display} --brightness #{brightness}`
  `echo #{brightness} > ~/.xbacklight`
end

def parse(str)
  if str.to_f <= 1.0
    clip(str.to_f, 0.0, 1.0)
  else
    clip(str.to_i / 100.0, 0.0, 1.0)
  end
end

brightness = `[ -f ~/.xbacklight ] && cat ~/.xbacklight || echo 0.9`.to_f
display = `xrandr | grep ' connected' | awk '{print $1}'`.chomp

while ARGV.size > 0
  case ARGV[0]
  when '-h', '--help'
    usage
  when '-display'
    display = ARGV[1]
    ARGV.shift
    ARGV.shift
  when '='
    x = parse(ARGV[1])
    brightness = x
    ARGV.shift
    ARGV.shift
  when '+'
    x = parse(ARGV[1])
    brightness += x
    ARGV.shift
    ARGV.shift
  when '-'
    x = parse(ARGV[1])
    brightness -= x
    ARGV.shift
    ARGV.shift
  else
    p (brightness * 100)
    exit 0
  end
end

update(display, brightness)
