#!/bin/bash

if [ $# -eq 0 ]; then
  cat << HELP
SYNOPSIS: xf <TERMINAL> [<mode>]
SYNOPSIS: xf off <TERMINAL>

xrandr -q
HELP
  xrandr -q
  exit 0
fi

if [ $1 == "off" ]; then

  TERMINAL=$2
  xrandr --output $TERMINAL --off

else

  TERMINAL=$1
  if [ $# -eq 2 ]; then
    MODE=$2
  else
    MODE=$( xrandr | grep -A100 $TERMINAL | tail -1 | awk '{print $1}' )
    MODE=$(
    xrandr -q | grep -A100 eDP1 |
    awk 'BEGIN{a=0}substr($0,0,1)!=" "{a+=1}a==1&&substr($0,0,1)==" "{print $1}' |
    peco
    )
  fi

  MAIN=$( xrandr -q | head -2 | tail -1 | awk '{print $1}' )
  echo xrandr --output $TERMINAL --right-of $MAIN --mode $MODE --auto
  xrandr --output $TERMINAL --right-of $MAIN --mode $MODE --auto

fi
