#!/bin/bash

## Help
help() {
  cat << HELP
NAME
    xr -- xrandr wrapper

SYNOPSIS
    xr {main|sub|off} [<monitor>] [<mode>]
      main -- main monitor
      sub  -- sub monitor (2nd display or projector)
      off  -- stop using the monitor
        Hint: try \`xrandr -q\` to see your monitors
      If monitor and mode are omitted, You can choose via peco.

    xr help
      Print this.
HELP
  exit 0
}

choose-monitor() {
  xrandr -q | grep ' connected' | awk '{print $1}' | peco
}

choose-mode() {
  xrandr -q | grep -A 100 $1 |
    awk "BEGIN { flg = 0 }
      /^ / && flg { print }
      !/^ / && flg { flg = 0 }
      \$1 == \"$1\" { flg = 1 }" |
    awk '{print $1}' |
    peco
}

xrand-off() {
  if [ "_$1" = "_" ]; then
    echo "No monitor selected"
    exit
  fi
  xrandr --output $1 --off
}

xrandr-main() {
  if [ "_$1" = "_" ]; then
    echo "No monitor selected"
    exit
  fi
  if [ "_$2" = "_" ]; then
    echo "No mode selected"
    exit
  fi
  xrandr --output $1 --mode $2 --auto
}

xrandr-sub() {
  if [ "_$1" = "_" ]; then
    echo "No monitor selected"
    exit
  fi
  if [ "_$2" = "_" ]; then
    echo "No mode selected"
    exit
  fi
  MAIN=$( xrandr -q | grep ' connected primary' | head -1 | awk '$0=$1' )
  xrandr --output $1 --right-of $MAIN --mode $2 --auto
}

[ $# -eq 0 ] && help

case "${1}_${2}_${3}" in
  off__ )
    xrandr-off "$(choose-monitor)"
    ;;

  off_* )
    xrandr-off "$2"
    ;;

  main__ )
    MONITOR="$(choose-monitor)"
    MODE="$(choose-mode "$MONITOR")"
    xrandr-main "$MONITOR" "$MODE"
    ;;

  main_*_ )
    MONITOR="$2"
    MODE="$(choose-mode "$MONITOR")"
    xrandr-main "$MONITOR" "$MODE"
    ;;

  main_*_* )
    xrandr-main "$2" "$3"
    ;;

  sub__ )
    MONITOR="$(choose-monitor)"
    MODE="$(choose-mode "$MONITOR")"
    xrandr-sub "$MONITOR" "$MODE"
    ;;

  sub_*_ )
    MONITOR="$2"
    MODE="$(choose-mode "$MONITOR")"
    xrandr-sub "$MONITOR" "$MODE"
    ;;

  sub_*_* )
    xrandr-sub "$2" "$3"
    ;;

  * )
    help
    ;;

esac

