#!/bin/bash

## Help
help() {
  cat << HELP
NAME
    xr -- xrandr wrapper

SYNOPSIS
    xr {main|sub|off} <monitor> [<mode>]
      main -- main monitor
      sub  -- sub monitor (2nd display or projector)
      off  -- stop using the monitor
      (try \`xrandr -q\` to see your monitors)

    xr q
      alias to \`xrandr -q\`
HELP
  exit 0
}

[ $# -eq 0 ] && help

case $1 in
  off )
    xrandr --output $2 --off
    ;;

  q )
    xrandr -q
    ;;

  main | sub )
    TERMINAL=$2
    MODE=$3

    # when TERMINAL is empty
    [ "_$TERMINAL" == "_" ] && help

    # filled by peco when MODE is empty
    if [ "_$MODE" == "_" ]; then
      MODE=$( xrandr -q | grep -A100 $TERMINAL |
        awk 'BEGIN{a=0}substr($0,0,1)!=" "{a+=1}a==1&&substr($0,0,1)==" "{print $1}' |
        peco
      )
    fi

    # when peco exits with C-c or something is wrong
    if [ "_$MODE" == "_" ]; then
      exit 0
    fi

    case $1 in

      main )
        xrandr --output $TERMINAL --mode $MODE --auto
        ;;

      sub )
        MAIN=$( xrandr -q | grep ' connected primary' | head -1 | awk '$0=$1' )
        xrandr --output $TERMINAL --right-of $MAIN --mode $MODE --auto
        ;;
    esac
    ;;

  * )
    help
    ;;

esac

