#!/usr/bin/env python

import click
import yaml


@click.command()
@click.argument('input', type=click.File('r'))
def main(input):
    try:
        yaml.safe_load(input)
    except Exception as e:
        print(e)
        click.secho('FAILED', err=True, fg='red')
        exit(1)


if __name__ == '__main__':
    main()
